---
permalink: exceptions
title: 异常处理
category: 基础
---

= 异常处理

toc::[]

AdonisJs 不仅将异常视为指导开发人员出错的方法，而且还将其作为围绕异常构建应用程序流的一种方式。

在本指南中，我们将学习如何引发异常，如何围绕异常编写逻辑，以及最终创建自己的自定义异常。

== 介绍
异常是个好东西，因为它们会在某个阶段停止程序，并在继续操作之前确保一切正确。

异常通常只是作为指导来告诉开发者出了什么问题，但是如果处理得当，它们可以可以帮助你围绕异常构建应用程序流。

默认情况下， AdonisJs 会帮你处理所有异常，并在开发过程中以 link:http://res.cloudinary.com/adonisjs/image/upload/v1485520687/Screen_Shot_2017-01-27_at_6.07.28_PM_blcaau.png[友好的格式, window="_blank"] 显示它们。但是，你也可以随意处理异常。

== 异常处理
可以通过绑定通配符异常处理程序或使用其名称处理单个异常来处理异常。

=== 通配符处理程序（通用处理程序）
让我们使用以下 `adonis` 命令创建一个通配符异常处理程序：

[source, bash]
----
> adonis make:ehandler
----

.make:ehandler output
[source, bash]
----
✔ create  app/Exceptions/Handler.js
----

一旦创建，通用异常处理程序就会传递 HTTP 生命周期中发生的所有异常：

.app/Exceptions/Handler.js
[source, js]
----
const BaseExceptionHandler = use('BaseExceptionHandler')

class ExceptionHandler extends BaseExceptionHandler {
  async handle (error, { response, session }) {
    if (error.name === 'ValidationException') {
      session.withErrors(error.messages).flashAll()
      await session.commit()
      response.redirect('back')
      return
    }

    return super.handle(...arguments)
  }
}

module.exports = ExceptionHandler
----

以上示例中，`handle` 方法通过将验证错误刷新回表单来处理 `ValidationException`。

=== 个别异常
你可以通过为这些异常定义内联处理程序来钩住（hook）它们。

这可以在 `start/hooks.js` 文件中完成：

.start/hooks.js
[source, js]
----
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
  const Exception = use('Exception')

  Exception.handle('ValidationException', async (error, { response, session }) => {
    session.withErrors(error.messages).flashAll()
    await session.commit()
    response.redirect('back')
    return
  })
})
----

== 自定义异常
使用AdonisJs可以轻松构建自己的自定义异常并为其定义处理程序。

让我们使用 `adonis` 命令创建自定义异常：

[source, bash]
----
> adonis make:exception Custom
----

.make:exception output
[source, bash]
----
✔ create  app/Exceptions/CustomException.js
----

.app/Exceptions/CustomException.js
[source, js]
----
const { LogicalException } = require('@adonisjs/generic-exceptions')

class CustomException extends LogicalException {}

module.exports = CustomException
----

你可以通过导入其源文件来抛出此异常（`status` 和 `code` 值是可选的）：

[source, js]
----
const CustomException = use('App/Exceptions/CustomException')

throw new CustomException(message, status, code)
----

你可以在自定义异常中设置默认消息、状态和代码：

.app/Exceptions/NotEditableException.js
[source, js]
----
const { LogicalException } = require('@adonisjs/generic-exceptions')
const message = 'The item is in an status where modifications are disallowed'
const status = 403
const code = 'E_NOT_EDITABLE'

class NotEditableException extends LogicalException {
  constructor () {
    super(message, status, code)
  }
}

module.exports = NotEditableException
----

[source, js]
----
const NotEditableException = use('App/Exceptions/NotEditableException')

throw new NotEditableException()
----

这种方法的优点在于，你可以将异常的唯一名称作为类名称，然后适当地捕获并响应它们。

=== 更进一步
通过在自定义异常类上定义 `handle` 和 `report` 方法，我们可以使自定义异常处理更进一步：

.app/Exceptions/CustomException.js
[source, js]
----
const { LogicalException } = require('@adonisjs/generic-exceptions')

class CustomException extends LogicalException {
  handle (error, { response }) {
    response
      .status(500)
      .send('Custom exception handled!')
  }
}

module.exports = CustomException
----

如果设置了，AdonisJs将调用自定义异常的 `handle` 方法来创建并返回异常响应。
